# Generated by Django 3.2.6 on 2021-10-09 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devices',
            name='id',
        ),
        migrations.AddField(
            model_name='devices',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devices',
            name='ipaddress',
            field=models.GenericIPAddressField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='devices',
            name='fqdn',
            field=models.CharField(max_length=10),
        ),
    ]
