# Generated by Django 3.2.6 on 2021-10-11 10:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_devices_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='CUC',
            fields=[
                ('ipaddress', models.GenericIPAddressField(default=None, primary_key=True, serialize=False)),
                ('fqdn', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('datetime', models.DateField(default=datetime.datetime(2021, 10, 11, 15, 43, 40, 129241))),
                ('creator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CUCM',
            fields=[
                ('ipaddress', models.GenericIPAddressField(default=None, primary_key=True, serialize=False)),
                ('fqdn', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('datetime', models.DateField(default=datetime.datetime(2021, 10, 11, 15, 43, 40, 129241))),
                ('creator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UCCX',
            fields=[
                ('ipaddress', models.GenericIPAddressField(default=None, primary_key=True, serialize=False)),
                ('fqdn', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('datetime', models.DateField(default=datetime.datetime(2021, 10, 11, 15, 43, 40, 129241))),
                ('creator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UCS',
            fields=[
                ('ipaddress', models.GenericIPAddressField(default=None, primary_key=True, serialize=False)),
                ('fqdn', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('datetime', models.DateField(default=datetime.datetime(2021, 10, 11, 15, 43, 40, 130233))),
                ('creator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Devices',
        ),
    ]
