# Generated by Django 3.2.6 on 2021-10-11 10:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20211011_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuc',
            name='datetime',
            field=models.DateField(default=datetime.datetime(2021, 10, 11, 10, 17, 11, 456810, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cucm',
            name='datetime',
            field=models.DateField(default=datetime.datetime(2021, 10, 11, 10, 17, 11, 455810, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='uccx',
            name='datetime',
            field=models.DateField(default=datetime.datetime(2021, 10, 11, 10, 17, 11, 456810, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ucs',
            name='datetime',
            field=models.DateField(default=datetime.datetime(2021, 10, 11, 10, 17, 11, 456810, tzinfo=utc)),
        ),
    ]
