# Generated by Django 3.2.6 on 2021-10-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20211011_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuc',
            name='hostname',
            field=models.CharField(default=None, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='cucm',
            name='hostname',
            field=models.CharField(default=None, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='uccx',
            name='hostname',
            field=models.CharField(default=None, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='ucs',
            name='hostname',
            field=models.CharField(default=None, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='cuc',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cucm',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='uccx',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ucs',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
