# Generated by Django 3.2.6 on 2021-10-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20211012_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuc',
            name='fqdn',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cucm',
            name='fqdn',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='uccx',
            name='fqdn',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ucs',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
